// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"time"
)

type User struct {
	ID            int32     `db:"id"`
	Name          string    `db:"name"`
	Password      string    `db:"password"`
	Email         string    `db:"email"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}
