// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"context"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error)
	GetTeam(ctx context.Context, id int32) (Team, error)
	GetTeamMembers(ctx context.Context, teamID int32) ([]TeamMember, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	VerifyEmail(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
