// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"context"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	VerifyEmail(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
